// <auto-generated />
using System;
using Ab_Kiros_ROM.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ab_Kiros_ROM.Migrations
{
    [DbContext(typeof(abContext))]
    [Migration("20200120151716_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ab_Kiros_ROM.Models.Illness", b =>
                {
                    b.Property<int>("illness_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("illness_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("illness_ID");

                    b.ToTable("illenses");
                });

            modelBuilder.Entity("Ab_Kiros_ROM.Models.Person", b =>
                {
                    b.Property<Guid>("person_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("active")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("contact_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("person_ID");

                    b.ToTable("persons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("Ab_Kiros_ROM.Models.Visits", b =>
                {
                    b.Property<int>("visits_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("client_ID")
                        .HasColumnType("int");

                    b.Property<int>("doctor_ID")
                        .HasColumnType("int");

                    b.HasKey("visits_ID");

                    b.ToTable("visits");
                });

            modelBuilder.Entity("Ab_Kiros_ROM.Models.Client", b =>
                {
                    b.HasBaseType("Ab_Kiros_ROM.Models.Person");

                    b.Property<int>("client_ID")
                        .HasColumnType("int");

                    b.Property<int>("illness_ID")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("Ab_Kiros_ROM.Models.Doctor", b =>
                {
                    b.HasBaseType("Ab_Kiros_ROM.Models.Person");

                    b.Property<string>("country_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("doctor_ID")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
